- hosts: kali
  remote_user: kali
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update-cache: yes
    become: yes
  - name: apt full-upgrade
    ansible.builtin.apt:
      upgrade: full
    become: yes
