- name: kali
  hosts: kali
  remote_user: kali
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update-cache: yes
    become: yes
  - name: apt full-upgrade
    ansible.builtin.apt:
      upgrade: full
    become: yes
  - name: Install kali-linux-headless metapackage
    ansible.builtin.apt:
      name: kali-linux-headless
      state: present
    become: yes
  - name: Install xfce and rdp
    ansible.builtin.apt:
      name:
        - kali-desktop-xfce
        - xorg
        - xrdp
      state: present
    become: yes
  - name: Enable and start rdp service
    ansible.builtin.systemd:
      name: xrdp
      state: started
      enabled: true
    become: yes
  - name: Set up kali user
    ansible.builtin.user:
      name: kali
      password: $6$XfE4ENWj54dMpO6l$3SSNhXD9n61xXFvrtod0iSqCnFeAV.2xL7Tnaa6v7.D3PMAjTQ6aklc6heTrdl3q4S2FaNFcmOlVFNMMU6OyO1
    become: yes
  - name: Listen on port 443 for sshd
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      line: Port 443
    become: yes
  - name: Uncomment port 22 for sshd_config
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regex: "^#Port 22"
      line: Port 22
    notify:
    - Restart sshd
    become: yes

  handlers:
    - name: Restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
      become: yes
