- name: chrome
  hosts: kali
  remote_user: kali
  tasks:
  - name: Add GPG key for veryifing package signature
    ansible.builtin.apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
    become: yes
