- name: OWASP Juice Shop
  hosts: vulnweb
  tasks:
  - name: Pull image
    community.docker.docker_image:
      name: bkimminich/juice-shop@sha256:073163e118541daec3a26321d6fb70e7454ab369de5f296c131f5ff99fc8c91c
      source: pull
  - name: Start container
    community.docker.docker_container:
      name: juice-shop
      image: bkimminich/juice-shop@sha256:073163e118541daec3a26321d6fb70e7454ab369de5f296c131f5ff99fc8c91c
      ports:
        - 80:3000
