- name: kali
  hosts: kali
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update-cache: yes
    become: yes
  - name: apt full-upgrade
    ansible.builtin.apt:
      upgrade: full
    become: yes
  - name: Install kali-linux-headless metapackage
    ansible.builtin.apt:
      name: kali-linux-headless
      state: present
    become: yes
  - name: Install xfce and rdp
    ansible.builtin.apt:
      name:
        - kali-desktop-xfce
        - xorg
        - xrdp
      state: present
    become: yes
  - name: Enable and start rdp service
    ansible.builtin.systemd:
      name: xrdp
      state: started
      enabled: true
    become: yes
  - name: Set up kali user
    ansible.builtin.user:
      name: kali
      password: $6$XfE4ENWj54dMpO6l$3SSNhXD9n61xXFvrtod0iSqCnFeAV.2xL7Tnaa6v7.D3PMAjTQ6aklc6heTrdl3q4S2FaNFcmOlVFNMMU6OyO1
    become: yes
  - name: Install Burp Suite
    ansible.builtin.apt:
      name: burpsuite
      state: present
    become: yes
