- name: vulnweb
  hosts: vulnweb
  tasks:
  - name: apt update
    ansible.builtin.apt:
      update-cache: yes
    become: yes
  - name: Install Docker
    ansible.builtin.apt:
      name:
        - docker.io
        - docker-compose
        - docker-doc
      state: present
    become: yes
  - name: Add user to docker Unix group
    ansible.builtin.user:
      name: vulnweb
      groups: docker
      append: yes
    become: yes
